<?php

function bemas_lang_redirect_init() {
  // see if we are on a civicrm page
  if (strpos($_SERVER['REQUEST_URI'], '/civicrm/event/register') !== FALSE) {
    // skip for confirmation and thank you screen, or when we don't have and id
    if (array_key_exists('_qf_Confirm_display', $_GET) || array_key_exists('_qf_ThankYou_display', $_GET) || !array_key_exists('id', $_GET)) {
      return;
    }

    // see if lcMessages is missing
    if (stripos($_SERVER['REQUEST_URI'], 'lcMessages') === FALSE) {
      // add the language switch and redirect
      $lang = '';

      if (strpos($_SERVER['REQUEST_URI'], '/nl/civicrm/event/register') !== FALSE) {
        $lang = 'nl_NL';
      }
      elseif (strpos($_SERVER['REQUEST_URI'], '/fr/civicrm/event/register') !== FALSE) {
        $lang = 'fr_FR';
      }
      elseif (strpos($_SERVER['REQUEST_URI'], '/en/civicrm/event/register') !== FALSE) {
        $lang = 'en_US';
      }

      if ($lang) {
        $queryParams = drupal_get_query_parameters();
        $queryParams['lcMessages'] = $lang;

        $newURL = (isset($_SERVER['HTTPS']) ? "https://" : "http://") . $_SERVER['HTTP_HOST'] . strtok($_SERVER['REQUEST_URI'],'?');
        drupal_goto($newURL, ['query' => $queryParams]);
      }
    }
  }
}
