<?php

function bemas_lang_redirect_init() {
  // see if we are on a civicrm page
  if (strpos($_SERVER['REQUEST_URI'], '/civicrm/event/register') !== FALSE) {
    // see if lcMessages is missing
    if (stripos($_SERVER['REQUEST_URI'], 'lcMessages') === FALSE) {
      // add the language switch and redirect
      $lang = '';

      if (strpos($_SERVER['REQUEST_URI'], '/nl/civicrm/event/register') !== FALSE) {
        $lang = 'nl_NL';
        $langPrefix = 'nl';
      }
      elseif (strpos($_SERVER['REQUEST_URI'], '/fr/civicrm/event/register') !== FALSE) {
        $lang = 'fr_FR';
        $langPrefix = 'fr';
      }
      elseif (strpos($_SERVER['REQUEST_URI'], '/en/civicrm/event/register') !== FALSE) {
        $lang = 'en_US';
        $langPrefix = 'en';
      }

      if ($lang) {
        $queryParams = drupal_get_query_parameters();
        $queryParams['lcMessages'] = $lang;

        $newURL = (isset($_SERVER['HTTPS']) ? "https://" : "http://") . $_SERVER['HTTP_HOST'] . strtok($_SERVER['REQUEST_URI'],'?');
        drupal_goto($newURL, ['query' => $queryParams]);
      }
    }
  }
}
